import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
  SignIn,
  SignUp,
} from "@clerk/nextjs";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
<ClerkProvider>
<html lang="en">
  <body>
    <header>
    </header>
    <main>{children}</main>
  </body>
</html>
</ClerkProvider>
  )
}


